Fix UTC Import error  for Python < 3.11 (#32)
* Adjust UTC for Python < 3.11

Fixes "ImportError: cannot import name 'UTC' from 'datetime'" as UTC shorthand was added in Python 3.11

* [pre-commit.ci] automatic pre-commit fixes

---------

Co-authored-by: pre-commit-ci[bot] <66853113+pre-commit-ci[bot]@users.noreply.github.com>